server:
  port: 9001
spring:
  application:
    name: si-config-svr
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajatmehta1/SecondInings/tree/master/si-config-repo
          search-paths: '{application}'
