server:
  port: 9002
spring:
#  security:
#    user:
#      name: root
#      password: root
  application:
    name: si-config-svr
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajatmehta1/SecondInings
          skip-ssl-validation: true
          username: rajat.me@gmail.com
          password: ilupreet1
          search-paths: 'si-config-repo/{profile}'
