spring:
  cloud:
  application:
    name: user-profile
#  cloud:
#    config:
#      uri : http://localhost:9002
#      username: root
#      password: rootspring.cloud.config.fail-fast=true
server:
  port: 9010
